<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWpUHilI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWpUHilI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWpUHilI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWpUHilI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWpUHilI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WpUHilI',
    'container.build_id' => '3c5f5150',
    'container.build_time' => 1644490485,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWpUHilI');
