<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ3oHWER\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ3oHWER/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ3oHWER.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ3oHWER\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZ3oHWER\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Z3oHWER',
    'container.build_id' => '9fed1f02',
    'container.build_time' => 1645090729,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ3oHWER');
