<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSsxQuu1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSsxQuu1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSsxQuu1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSsxQuu1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSsxQuu1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SsxQuu1',
    'container.build_id' => 'c700cfbd',
    'container.build_time' => 1645021500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSsxQuu1');
